### ISSUE TITLE
re new drawing system

### ISSUE THREAD

**Issue by sdsddsd1** [djt3/tuitube#4]
hola!
After recent update the ui got a bit buggy. Tested with alacritty and wterm. Both similar.
- After the cursor reached the lower end to start scrolling it takes a moment until scrolling starts.
It also takes some time when you start scrolling up again.
- After starting a video, the mpv info lines in the upper side doesnt get drawn properly.
Mpv status is mixed with the channel supscriptions.
- After the video is closed the ui is not properly redrawn -> rests of mpv info are seen.
- Selecting a channels name does open the wrong channel after a video was played.

[Screenshot](https://ibb.co/j4VvZpr)

**Comment by djt3** [comment]
![2020-05-12-181353_1920x1080_scrot](https://user-images.githubusercontent.com/60714836/81724520-06d59800-9474-11ea-9c17-4f6390627875.png)

Hi! Thanks for reporting this:)
I will have to start doing some testing with other terminals, since this new drawing method works fine with the st terminal (as seen in the screenshot). You can expect this to be fixed in the next day or two

**Comment by djt3** [comment]
Fixed in the latest push. feel free to reopen the issue if there is still anything wrong with the new drawing system

**Comment by sdsddsd1** [comment]
Latest commit `05164c7`  makes tuitube segfaulting. Tested in alacritty and st.
