### ISSUE TITLE
[Feature Request] Audio only mode

### ISSUE THREAD

**Issue by ghost** [djt3/tuitube#7]
Would it be possible to add mode for playing only audio? Mpv has --no-video option but it'd be nice to have better option than editing mpv.conf only when using tuitube.

Edit: I realized it might also be done by adding --no-video to mpv in config.h but then the program would need to be rebuild to change that back.

**Comment by djt3** [comment]
yeah i didn't think of this as a feature, thanks for suggesting it. adding an audio only mode is as simple as adding "&listen=1" to the end of the invidious url, so i'll be doing it that way since it saves bandwidth as opposed to the --no-video flag, and also ensures more compatibility if someone were to change the default player. ill be adding this in the next day or two.

**Comment by djt3** [comment]
added in the latest commit
