### ISSUE TITLE
Some minor suggestions 

### ISSUE THREAD

**Issue by sdsddsd1** [djt3/tuitube#9]
Hey,
here are some thoughts that came to my mind while I was using your great little tool on a regular basis to satisfy my youtube needs. Please note that I have no real idea on what is going on under the hood, so my suggestions are based on what I see and what I believe can be aranged.
  

- **Subscriptions**: Align upload date and duration on the right side of the screen for better overall view.

- **Sublist**: There is space to print also the last date of update.(On the right side of the screen)
  Sort sublist by alphabet, since the subscriptions are already sorted by date. I personaly use the the sublist to look for a specific channel.
  I think to switch between sublist/subscriptions by a dedicated key is great!(Keep the functions on TAB small)

- **Search**: In the upper statusline, there is space to display $SEARCHTERM

- **Lower statusline**: `Grouping of elements`. There are many elements and unused space on the right. Move groups to the outer edges  
  
     - `play specific`:              play, audio only, display channel link(for download)
     - `channel managment`: un/subscribe, refresh, change tab.  
  
    NOTE:   "view channel" and "back" are already left out. See Key asigment below.
    NOTE2: Is "quit" really necessary? This could be assumed intuitive and improve overview.

- **Key asigment**: c=view b=back => h=back l=view
  would make consistent vimkey usage. Less stuff to display in the status line since this is intuitive.
  At least for some folks. At the moment I want intuitively open an item from the sublist with enter which opens then a video from the subsciption view.  
  
  It happened that I accidentially added or deleted subscriptions. Since this is a delicate action,
  a key combo or yes/no input might be worth it. (C-s / C-u)

- **Download link**: Add a keybinding for "display link" which can be copied by hand. I guess specifying an interchangeable clipboardtool might be complicated and error prone.

- Mpv has the bad behaviour to let the user wait until the video opens. Also when the video does not open at all, nothing just has happend but waiting. (:
   -> Add another view, when mpv is invoked with "video loading"(blinking or fancy moving stuff?) This is then over drawn from mpv like it is now. This new view would also "fix" the issue that the list is just over drawn in pieces and a lot of damaged output is leftover. So this might not be noticeable.
     NOTE: This is just a vague asumption!

**Comment by djt3** [comment]
hey, thanks so much for making such an in-depth post :)
i will be working through a lot of these suggestions, since they are all great ideas, especially the status suggestion, that would make it look a lot cleaner imo.
however, with the bindings, i wanted to make them intuitive to people who aren't great at vim, since i'm not familiar with vim bindings myself.

**Comment by sdsddsd1** [comment]
I probably shouldnt have used such a big term like vim keys for a small meaning (:, though I just mean the keys for navigation.
It came to my mind to add a view for just the help bindings like it is done in ranger e.g. This way the working UI can stay as clean as it is possible while also providing a good in program documentation.
I also think that the vim folks will intuitively use hjkl, as any other folks probably the arrow keys. Why not support both?
I am glad you find value in my post!

**Comment by djt3** [comment]
i'm closing this issue for now because I've implemented all of the changes you suggested that I agree with. i chose not to implement your suggestion about the bottom status bar, as having two sets of bindings gave it a messy appearance. i'm still not too sure about the navigation keys, i feel like it is intuitive enough as is, regardless of weather or not you are used to vim key bindings, so please reopen the issue if you have any more feedback or suggestions :)
